### ISSUE TITLE
Can't send request to odoo.

### ISSUE THREAD

**Issue by abokerba** [akretion/angular-odoo#13]
XMLHttpRequest cannot load http://localhost:8069/web/webclient/version_info. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 400.

**Comment by ssaid** [comment]
Hi @abokerba I'm currently facing the same error, I think the only way to overcome this is patching wsgi_server.py and adding the header like here

`
start_response("200 OK", [('Content-Type','text/xml'), ('Content-Length', str(len(response))),
                        ('Access-Control-Allow-Origin','*'),
                        ('Access-Control-Allow-Methods','POST, GET, OPTIONS'),
                        ('Access-Control-Max-Age',1000),
                        ('Access-Control-Allow-Headers','origin, x-csrftoken, content-type, accept'),
        ])
`

If anyone knows another way it would be appreciated

**Comment by abokerba** [comment]
@ssaid  thank you!!

I had overcome this by making a new module for my project to handle http request from my application.

**Comment by sebastienbeau** [comment]
Hi, sorry to respond so late.
In fact you should not change the wsgi_server.py because allowing CORS will be a major security issue (anybody will be able to do an DDOS attack on your ERP from JS client).
What you need to do is to serve your application on the same domain/port.
2 possibility:
- serving your application using nginx/apache and configuring a path reserved for your application. Something like http://my.domain.com/my_application => m.domain.com is the erp and my.domain.com/my_application is the application
- serving your application like an odoo module you can see exemple here :https://github.com/akretion/odooapps, https://github.com/akretion/odooapps/tree/8.0/prodoo/static/apps
